# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PerseDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  # Pods for PerseDemo
  pod 'Perse', :path => '../../'
end

target 'PerseDemoTests' do    
    pod 'Perse', :path => '../../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
