public enum HeadMovement {
    case UNDEFINED
    case VERTICAL_UP
    case VERTICAL_SUPER_UP
    case VERTICAL_NORMAL
    case VERTICAL_DOWN
    case VERTICAL_SUPER_DOWN
    case HORIZONTAL_LEFT
    case HORIZONTAL_SUPER_LEFT
    case HORIZONTAL_NORMAL
    case HORIZONTAL_RIGHT
    case HORIZONTAL_SUPER_RIGHT
    case TILT_LEFT
    case TILT_SUPER_LEFT
    case TILT_NORMAL
    case TILT_RIGHT
    case TILT_SUPER_RIGHT
}
